apiVersion: v1
kind: Service
metadata:
 name: appnode-s
spec:
 selector:
   role: app
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 32001
 type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: appnode-d
 labels:
   role: app
spec:
 replicas: 3
 selector:
   matchLabels:
     role: app
 template:
   metadata:
     labels:
       role: app
   spec:
     containers:
     - name: app
       image: "bharathpantala/node:1.1.0"
     - name: web
       image: "bharathpantala/nginx:2.0"
